# Generated by Django 5.0.2 on 2024-02-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
