# Generated by Django 5.0.2 on 2024-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_projects_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
