# Generated by Django 5.0.2 on 2024-03-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_skill_delete_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.CharField(max_length=600),
        ),
    ]
