# Generated by Django 5.0.2 on 2024-03-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_summary_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
