# Generated by Django 5.0.2 on 2024-03-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_summary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='school_description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
