# Generated by Django 5.0.2 on 2024-03-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_schools_school_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_description',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
    ]
