# Generated by Django 5.0.2 on 2024-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_companies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
    ]
