# Generated by Django 5.0.2 on 2024-03-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_vlogcategory_vlogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogpost',
            name='vlogPost_description',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
    ]
