# Generated by Django 5.0.2 on 2024-03-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_vlogpost_vlogpost_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
