# Generated by Django 5.0.2 on 2024-03-09 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_ID', models.CharField(default='Not Stated', max_length=4)),
                ('project_name', models.CharField(default='Not Stated', max_length=50)),
                ('project_date', models.DateField(default=datetime.date.today)),
                ('project_link', models.CharField(default='Not Stated', max_length=500)),
                ('project_picture', models.CharField(default='Not Stated', max_length=500)),
                ('project_description', models.CharField(default='Not Stated', max_length=2000)),
            ],
        ),
    ]
