# Generated by Django 5.0.2 on 2024-03-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
