# Generated by Django 5.0.2 on 2024-03-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_ID', models.CharField(default='Not Stated', max_length=4)),
                ('profile_name', models.CharField(default='Not Stated', max_length=50)),
                ('profile_email', models.CharField(default='Not Stated', max_length=50)),
                ('profile_phone', models.CharField(default='Not Stated', max_length=20)),
                ('profile_city', models.CharField(default='Not Stated', max_length=20)),
                ('profile_province', models.CharField(default='Not Stated', max_length=2)),
                ('profile_picture', models.CharField(default='Not Stated', max_length=500)),
                ('profile_status', models.CharField(default='0', max_length=1)),
                ('profile_bio', models.CharField(default='Not Stated', max_length=4000)),
                ('profile_summary', models.CharField(default='Not Stated', max_length=4000)),
            ],
        ),
    ]
