# Generated by Django 5.0.2 on 2024-03-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schools',
        ),
        migrations.DeleteModel(
            name='summary',
        ),
    ]
