# Generated by Django 5.0.2 on 2024-03-09 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_delete_schools_delete_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_ID', models.CharField(default='Not Stated', max_length=4)),
                ('profile_ID', models.CharField(default='Not Stated', max_length=4)),
                ('education_schoolname', models.CharField(default='Not Stated', max_length=50)),
                ('education_schoolprogram', models.CharField(default='Not Stated', max_length=50)),
                ('education_schoolcity', models.CharField(default='Not Stated', max_length=50)),
                ('education_schoolprovince', models.CharField(default='Not Stated', max_length=2)),
                ('education_programstart', models.DateField(default=datetime.date.today)),
                ('education_programend', models.DateField(default=datetime.date.today)),
                ('education_programdescription', models.CharField(default='Not Stated', max_length=2000)),
            ],
        ),
    ]
