# Generated by Django 5.0.2 on 2024-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_ID', models.CharField(default='Not Stated', max_length=4)),
                ('education_ID', models.CharField(default='Not Stated', max_length=4)),
                ('course_name', models.CharField(default='Not Stated', max_length=4)),
                ('course_description', models.CharField(default='Not Stated', max_length=4000)),
            ],
        ),
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_course',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_position',
        ),
        migrations.AddField(
            model_name='skill',
            name='course_ID',
            field=models.CharField(default='Not Stated', max_length=4),
        ),
        migrations.AddField(
            model_name='skill',
            name='project_ID',
            field=models.CharField(default='Not Stated', max_length=4),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_ID',
            field=models.CharField(default='Not Stated', max_length=4),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_desccription',
            field=models.CharField(default='Not Stated', max_length=2000),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default='Not Stated', max_length=50),
        ),
    ]
