# Generated by Django 5.0.2 on 2024-03-10 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_course_delete_courses_remove_skill_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_ID', models.CharField(default='Not Stated', max_length=4)),
                ('profile_ID', models.CharField(default='Not Stated', max_length=4)),
                ('experience_name', models.CharField(default='Not Stated', max_length=50)),
                ('experience_position', models.CharField(default='Not Stated', max_length=50)),
                ('experience_city', models.CharField(default='Not Stated', max_length=50)),
                ('experience_province', models.CharField(default='Not Stated', max_length=2)),
                ('experience_start', models.DateField(default=datetime.date.today)),
                ('experience_end', models.DateField(default=datetime.date.today)),
                ('experience_description', models.CharField(default='Not Stated', max_length=4000)),
            ],
        ),
        migrations.DeleteModel(
            name='companies',
        ),
    ]
