# Generated by Django 5.0.2 on 2024-03-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_experience_delete_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_ID',
            field=models.CharField(default='Not Stated', max_length=20),
        ),
    ]
